FROM nvcr.io/nvidia/l4t-ml:r32.6.1-py3
RUN pip3 install --upgrade pip
RUN pip3 install flask opencv-python
RUN pip3 install pycuda
RUN pip3 install nvidia-pyindex
RUN apt install cuda-core-10-0
RUN add-apt-repository -y "deb https://repo.download.nvidia.com/jetson/common r32 main"
RUN add-apt-repository -y "deb https://repo.download.nvidia.com/jetson/t210 r32 main"
WORKDIR /app
COPY *.py /app/
RUN mkdir /app/faces
COPY faces /app/faces
ENV FLASK_APP=server
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PATH="$PATH:/usr/local/cuda-10.0/bin"
ENV LD_LIBRARY_PATH="/usr/local/cuda-10.0/lib64"${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
CMD python3 -m flask run --host 0.0.0.0
